apiVersion: batch/v1
kind: Job
metadata:
  name: '{{jobName}}'
spec:
  template:
    metadata:
      name: '{{jobName}}'
    spec:
      containers:
        - name: '{{jobName}}'
          image: '{{lang}}'
          imagePullPolicy: 'Always'
          resources:
            limits:
              cpu: '0.2'
              memory: '256Mi'
            requests:
              cpu: '0.1'
              memory: '256Mi'
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: '{{sharePath}}'
      restartPolicy: Never
      imagePullPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-nfs
  backoffLimit: 2
