image:
  file: .gitpod.Dockerfile
tasks:
  - name: init
    init: |
      yarn --cwd web install
    before: |
      printf "credentials \"app.terraform.io\" { \ntoken = \"${TFE_TOKEN}\" \n}\n" > ~/.terraformrc
    command: |
      yarn --cwd web dev

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - esbenp.prettier-vscode
