image:
  file: .gitpod.Dockerfile
tasks:
  - init: cat ${GITPOD_REPO_ROOT}/before.sh >> ~/.zshrc
  - init: printf "credentials \"app.terraform.io\" { \ntoken = \"${TFE_TOKEN}\" \n}\n" > ~/.terraformrc 

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - esbenp.prettier-vscode
    - humao.rest-client
