image:
  file: .gitpod.Dockerfile
tasks:
  - name: git
    before: |
      git config pull.rebase true
      alias rebase="git pull origin main:main && git rebase main"
  - command: printf "credentials \"app.terraform.io\" { \ntoken = \"${TFE_TOKEN}\" \n}\n" > ~/.terraformrc 

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - esbenp.prettier-vscode
    - humao.rest-client
