image:
  file: .gitpod.Dockerfile
tasks:
  - name: init
    init: |
      yarn --cwd web install
    before: |
      printf "credentials \"app.terraform.io\" { \ntoken = \"${TFE_TOKEN}\" \n}\n" > ~/.terraformrc
      git config pull.rebase true
      alias rebase="git pull origin main:main && git rebase main"
      unalias gp
      export PATH=$PATH:$GITPOD_REPO_ROOT/scripts
    command: |
      yarn --cwd web dev

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - esbenp.prettier-vscode
    - ms-python.python
