image:
  file: .gitpod.Dockerfile
tasks:
  - name: before.sh
    before: chmod +x before.sh && source before.sh
  - command: printf "credentials \"app.terraform.io\" { \ntoken = \"${TFE_TOKEN}\" \n}\n" > ~/.terraformrc 

vscode:
  extensions:
    - hashicorp.terraform
    - github.vscode-pull-request-github
    - esbenp.prettier-vscode
    - humao.rest-client
