version: "3.9"
services:
  java:
    build:
      context: .
      dockerfile: java/Dockerfile
    image: ${REPO}runner-java:latest
  golang:
    build:
      context: .
      dockerfile: golang/Dockerfile
    image: ${REPO}runner-go:latest
