name: backend-api

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/api/**'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend/api
          push: true
          tags: ghcr.io/${{ github.repository }}/backend-api:${{ github.sha }}
      #update terraform cloud variable
      - name: Update latest tag in terraform
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://app.terraform.io/api/v2/workspaces/ws-yXoXRjPNNYVvpWYm/vars/var-6MXNkbBNMoD8TYBd'
          method: 'PATCH'
          data: |
                  {
                    "data": {
                      "type":"vars",
                      "attributes": {
                        "key":"backend-api-tag",
                        "value":"ghcr.io/${{ github.repository }}/backend-api:${{ github.sha }} > backend-api.tag",
                        "category":"terraform",
                        "hcl":false,
                        "sensitive":false
                      }
                    }
                  }
          bearerToken: ${{ secrets.TERRAFORM_API_TOKEN }}