name: backend-api

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/api/**'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/api
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend/api
          push: true
          tags: ghcr.io/${{ github.repository }}/backend-api:${{ github.sha }}
      #store latest image details for later use
      - run: echo ghcr.io/${{ github.repository }}/backend-api:${{ github.sha }} > backend-api.tag
      - uses: actions/upload-artifact@v2
        with:
          name: backend-api.tag
          path: backend-api.tag