name: executor

on:
  push:
    branches: [main]
    paths:
      - "executor/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./executor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            base:
              - 'executor/base.Dockerfile'
            runnerBase:
              - 'executor/runner-base.Dockerfile'
      - name: Build and push base docker image
        if: steps.changes.outputs.base == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./executor
          file: executor/base.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/executor-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push base docker image
        if: steps.changes.outputs.base == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ./executor
          file: executor/runner-base.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/executor-runner-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push executor-api
        uses: docker/build-push-action@v3
        with:
          context: ./executor
          target: executor-api
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}/executor-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push executor
        uses: docker/build-push-action@v2
        with:
          context: ./executor
          target: executor
          pull: true
          push: true
          tags: ghcr.io/${{ github.repository }}/executor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Update latest tag in terraform
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://app.terraform.io/api/v2/workspaces/ws-yXoXRjPNNYVvpWYm/vars/var-534ENX4g3tcCnzjs"
          method: "PATCH"
          data: |
            {
              "data": {
                "type":"vars",
                "attributes": {
                  "key":"executor-api-tag",
                  "value":"ghcr.io/${{ github.repository }}/executor-api:${{ github.sha }}",
                  "category":"terraform",
                  "hcl":false,
                  "sensitive":false
                }
              }
            }
          bearerToken: ${{ secrets.TERRAFORM_API_TOKEN }}
          contentType: application/vnd.api+json
  deploy:
    uses: anuragashok/faster.codes/.github/workflows/terraform.yml@main
    needs: build
    secrets:
      GITHUB_TOKEN_COPY: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_API_TOKEN: ${{ secrets.TERRAFORM_API_TOKEN }}
