name: executor

on:
  push:
    branches: [main]
    paths:
      - "executor/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./executor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push executor-api
        uses: docker/build-push-action@v2
        with:
          context: ./executor
          target: executor-api
          push: true
          tags: ghcr.io/${{ github.repository }}/executor-api:${{ github.sha }}
      - name: Build and push executor
        uses: docker/build-push-action@v2
        with:
          context: ./executor
          target: executor
          push: true
          tags: ghcr.io/${{ github.repository }}/executor:latest
      - name: Update latest tag in terraform
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://app.terraform.io/api/v2/workspaces/ws-yXoXRjPNNYVvpWYm/vars/var-6MXNkbBNMoD8TYBd"
          method: "PATCH"
          data: |
            {
              "data": {
                "type":"vars",
                "attributes": {
                  "key":"executor-api-tag",
                  "value":"ghcr.io/${{ github.repository }}/executor-api:${{ github.sha }}",
                  "category":"terraform",
                  "hcl":false,
                  "sensitive":false
                }
              }
            }
          bearerToken: ${{ secrets.TERRAFORM_API_TOKEN }}
          contentType: application/vnd.api+json
  deploy:
    uses: anuragashok/faster.codes/.github/workflows/terraform.yml@main
    needs: build
    secrets:
      GITHUB_TOKEN_COPY: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_API_TOKEN: ${{ secrets.TERRAFORM_API_TOKEN }}
