name: web

on:
  push:
    branches: [main]
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn export

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: web-static-html
          FOLDER: web/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
